{{- if .Values.admissionWebhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "hmc.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ include "hmc.webhook.certNamespace" . }}/{{ include "hmc.webhook.certName" . }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /mutate-hmc-mirantis-com-v1alpha1-clusterdeployment
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: mutation.clusterdeployment.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusterdeployments
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /mutate-hmc-mirantis-com-v1alpha1-management
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: mutation.management.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - managements
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /mutate-hmc-mirantis-com-v1alpha1-clustertemplate
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: mutation.clustertemplate.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clustertemplates
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /mutate-hmc-mirantis-com-v1alpha1-servicetemplate
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: mutation.servicetemplate.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - servicetemplates
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /mutate-hmc-mirantis-com-v1alpha1-providertemplate
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: mutation.providertemplate.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - providertemplates
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "hmc.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ include "hmc.webhook.certNamespace" . }}/{{ include "hmc.webhook.certName" . }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-clusterdeployment
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.clusterdeployment.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - clusterdeployments
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-multiclusterservice
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.multiclusterservice.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - multiclusterservices
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-management
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.management.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - managements
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-clustertemplate
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.clustertemplate.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - DELETE
        resources:
          - clustertemplates
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-servicetemplate
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.servicetemplate.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - DELETE
        resources:
          - servicetemplates
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-providertemplate
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.providertemplate.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - DELETE
        resources:
          - providertemplates
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-accessmanagement
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.accessmanagement.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - accessmanagements
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-clustertemplatechain
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.clustertemplatechain.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - clustertemplatechains
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-servicetemplatechain
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.servicetemplatechain.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - servicetemplatechains
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-release
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.release.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - DELETE
        resources:
          - releases
    sideEffects: None
{{- end }}
