{{- if .Values.admissionWebhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "hmc.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ include "hmc.webhook.certNamespace" . }}/{{ include "hmc.webhook.certName" . }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /mutate-hmc-mirantis-com-v1alpha1-managedcluster
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: mutation.managedcluster.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - managedclusters
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /mutate-hmc-mirantis-com-v1alpha1-management
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: mutation.management.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - managements
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "hmc.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ include "hmc.webhook.certNamespace" . }}/{{ include "hmc.webhook.certName" . }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-managedcluster
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.managedcluster.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - managedclusters
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-management
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.management.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - managements
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-clustertemplate
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.clustertemplate.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - DELETE
        resources:
          - clustertemplates
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-servicetemplate
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.servicetemplate.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - DELETE
        resources:
          - servicetemplates
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-templatemanagement
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.templatemanagement.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - templatemanagements
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-clustertemplatechain
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.clustertemplatechain.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - clustertemplatechains
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "hmc.webhook.serviceName" . }}
        namespace: {{ include "hmc.webhook.serviceNamespace" . }}
        path: /validate-hmc-mirantis-com-v1alpha1-servicetemplatechain
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.servicetemplatechain.hmc.mirantis.com
    rules:
      - apiGroups:
          - hmc.mirantis.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - servicetemplatechains
    sideEffects: None
{{- end }}
