{{- if .Values.installBeachHeadServices }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  labels:
    hmc.mirantis.com/managed: "true"
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "cluster.name" . }}-cert-manager
  labels:
    hmc.mirantis.com/managed: "true"
spec:
  chart:
    metadata:
      labels:
        hmc.mirantis.com/managed: "true"
    spec:
      chart: cert-manager
      version: "v1.12.3"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 10m
  kubeConfig:
    secretRef:
      name: {{ include "cluster.name" . }}-kubeconfig
  releaseName: cert-manager
  targetNamespace: cert-manager
  storageNamespace: cert-manager
  values:
    installCRDs: true
{{- end }}
