apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "cluster-api-provider-aws.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "cluster-api-provider-aws.labels" . | nindent 4 }}
spec:
  selfSigned: {}
