apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0sControlPlane
metadata:
  name: {{ include "k0scontrolplane.name" . }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version }}
  k0sConfigSpec:
    {{- if .Values.airgap }}
    downloadURL: {{ required ".Values.k0s.downloadURL is required on airgap deployment" .Values.k0s.downloadURL }}
    {{- end }}
    files:
      - path: /home/{{ .Values.controlPlane.ssh.user }}/.ssh/authorized_keys
        permissions: "0600"
        content: "{{ trim .Values.controlPlane.ssh.publicKey }}"
    preStartCommands:
      {{- if .Values.airgap }}
      - mkdir -p /var/lib/k0s/images
      - curl -fsL {{ required ".Values.k0s.bundleURL is required on airgap deployment" .Values.k0s.bundleURL }} -o /var/lib/k0s/images/k0s-airgap-bundle
      {{- end }}
      - chown {{ .Values.controlPlane.ssh.user }} /home/{{ .Values.controlPlane.ssh.user }}/.ssh/authorized_keys
      - sed -i 's/"externalAddress":"{{ .Values.controlPlaneEndpointIP }}",//' /etc/k0s.yaml
    args:
      - --enable-worker
      - --disable-components=konnectivity-server
    k0s:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          sans:
            - {{ .Values.controlPlaneEndpointIP }}
          extraArgs:
            anonymous-auth: "true"
        network:
          provider: calico
          calico:
            mode: vxlan
        extensions:
          helm:
            repositories:
            - name: kube-vip
              url: https://kube-vip.github.io/helm-charts
            - name: vsphere-cpi
              url: https://kubernetes.github.io/cloud-provider-vsphere
            - name: mirantis
              url: https://charts.mirantis.com
            charts:
            - name: kube-vip
              chartname: kube-vip/kube-vip
              version: 0.6.1
              order: 1
              namespace: kube-system
              values: |
                {{- if .Values.extensions.imageRepository }}
                image:
                  repository: {{ .Values.extensions.imageRepository }}/kube-vip
                {{- end }}
                config:
                  address: {{ .Values.controlPlaneEndpointIP }}
                env:
                  svc_enable: "true"
                  cp_enable: "true"
                  lb_enable: "false"
                nodeSelector:
                  node-role.kubernetes.io/control-plane: "true"
                tolerations:
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/master
                    operator: Exists
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/control-plane
                    operator: Exists
                  - effect: NoSchedule
                    key: node.cloudprovider.kubernetes.io/uninitialized
                    value: "true"
            - name: vsphere-cpi
              chartname: vsphere-cpi/vsphere-cpi
              version: 1.31.0
              order: 2
              namespace: kube-system
              values: |
                config:
                  enabled: false
                daemonset:
                  {{- if .Values.extensions.imageRepository }}
                  image: {{ .Values.extensions.imageRepository }}/cloud-provider-vsphere
                  {{- end }}
                  tolerations:
                    - effect: NoSchedule
                      key: node.cloudprovider.kubernetes.io/uninitialized
                      value: "true"
                    - effect: NoSchedule
                      key: node-role.kubernetes.io/master
                      operator: Exists
                    - effect: NoSchedule
                      key: node-role.kubernetes.io/control-plane
                      operator: Exists
                    - effect: NoSchedule
                      key: node.kubernetes.io/not-ready
                      operator: Exists
                    - key: CriticalAddonsOnly
                      effect: NoExecute
                      operator: Exists
            - name: vsphere-csi-driver
              chartname: mirantis/vsphere-csi-driver
              version: 0.0.2
              order: 3
              namespace: kube-system
              values: |
                vcenterConfig:
                  enabled: false
                node:
                  kubeletPath: /var/lib/k0s/kubelet
                defaultStorageClass:
                  enabled: true
                images:
                  driver:
                    {{- if .Values.extensions.imageRepository }}
                    repo: {{ .Values.extensions.imageRepository }}/csi-vsphere/driver
                    {{- end }}
                    tag: v3.1.2
                  syncer:
                    {{- if .Values.extensions.imageRepository }}
                    repo: {{ .Values.extensions.imageRepository }}/csi-vsphere/syncer
                    {{- end }}
                    tag: v3.1.2
                  {{- if .Values.extensions.imageRepository }}
                  nodeDriverRegistrar:
                    repo: {{ .Values.extensions.imageRepository }}/sig-storage/csi-node-driver-registrar
                  csiAttacher:
                    repo: {{ .Values.extensions.imageRepository }}/sig-storage/csi-attacher
                  csiResizer:
                    repo: {{ .Values.extensions.imageRepository }}/sig-storage/csi-resizer
                  csiProvisioner:
                    repo: {{ .Values.extensions.imageRepository }}/sig-storage/csi-provisioner
                  csiSnapshotter:
                    repo: {{ .Values.extensions.imageRepository }}/sig-storage/csi-snapshotter
                  livenessProbe:
                    repo: {{ .Values.extensions.imageRepository }}/csi-vsphere/livenessprobe
                  {{- end }}
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: VSphereMachineTemplate
      name: {{ include "vspheremachinetemplate.controlplane.name" . }}
      namespace: {{ .Release.Namespace }}
