apiVersion: v2
name: projectsveltos
description: A Helm chart to refer the official projectsveltos helm chart
type: application
version: 0.38.1
appVersion: "0.38.1"
dependencies:
  - name: projectsveltos
    version: 0.38.1
    repository: https://projectsveltos.github.io/helm-charts
annotations:
  hmc.mirantis.com/type: provider
