---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - awsproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - awsproviders/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - awsproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managements/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managements/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - templates/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - templates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmcharts
  - helmrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
