# permissions for end users to edit backups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    hmc.mirantis.com/aggregate-to-global-admin: "true"
  name: {{ include "hmc.fullname" . }}-backup-editor-role
rules:
- apiGroups:
  - hmc.mirantis.com
  resources:
  - backups
  - backups/status
  verbs: {{ include "rbac.editorVerbs" . | nindent 6 }}
- apiGroups:
  - velero.io
  resources:
  - '*'
  verbs: {{ include "rbac.editorVerbs" . | nindent 6 }}
