apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version | replace "+" "-" }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  controllerPlaneFlags:
  - "--enable-cloud-provider=true"
  - "--debug=true"
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      network:
        provider: calico
        calico:
          mode: vxlan
      extensions:
        helm:
          repositories:
          - name: vsphere-cpi
            {{- if .Values.extensions.chartRepository }}
            url: {{ .Values.extensions.chartRepository }}
            {{- else }}
            url: https://kubernetes.github.io/cloud-provider-vsphere
            {{- end }}
          - name: mirantis
            {{- if .Values.extensions.chartRepository }}
            url: {{ .Values.extensions.chartRepository }}
            {{- else }}
            url: https://charts.mirantis.com
            {{- end }}
          charts:
          - name: vsphere-cpi
            chartname: vsphere-cpi/vsphere-cpi
            version: 1.31.0
            order: 1
            namespace: kube-system
            values: |
              config:
                enabled: false
              daemonset:
                affinity: null
                {{- if .Values.extensions.imageRepository }}
                image: {{ .Values.extensions.imageRepository }}/cloud-provider-vsphere
                {{- end }}
                tolerations:
                  - effect: NoSchedule
                    key: node.cloudprovider.kubernetes.io/uninitialized
                    value: "true"
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/master
                    operator: Exists
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/control-plane
                    operator: Exists
                  - effect: NoSchedule
                    key: node.kubernetes.io/not-ready
                    operator: Exists
                  - key: CriticalAddonsOnly
                    effect: NoExecute
                    operator: Exists
          - name: vsphere-csi-driver
            chartname: mirantis/vsphere-csi-driver
            version: 0.0.2
            order: 2
            namespace: kube-system
            values: |
              vcenterConfig:
                enabled: false
              controller:
                nodeAffinity: null
              node:
                kubeletPath: /var/lib/k0s/kubelet
              defaultStorageClass:
                enabled: true
              images:
                driver:
                  {{- if .Values.extensions.imageRepository }}
                  repo: {{ .Values.extensions.imageRepository }}/csi-vsphere/driver
                  {{- end }}
                  tag: v3.1.2
                syncer:
                  {{- if .Values.extensions.imageRepository }}
                  repo: {{ .Values.extensions.imageRepository }}/csi-vsphere/syncer
                  {{- end }}
                  tag: v3.1.2
                {{- if .Values.extensions.imageRepository }}
                nodeDriverRegistrar:
                  repo: {{ .Values.extensions.imageRepository }}/sig-storage/csi-node-driver-registrar
                csiAttacher:
                  repo: {{ .Values.extensions.imageRepository }}/sig-storage/csi-attacher
                csiResizer:
                  repo: {{ .Values.extensions.imageRepository }}/sig-storage/csi-resizer
                csiProvisioner:
                  repo: {{ .Values.extensions.imageRepository }}/sig-storage/csi-provisioner
                csiSnapshotter:
                  repo: {{ .Values.extensions.imageRepository }}/sig-storage/csi-snapshotter
                livenessProbe:
                  repo: {{ .Values.extensions.imageRepository }}/csi-vsphere/livenessprobe
                {{- end }}
