apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: {{ include "k0sworkerconfigtemplate.name" . }}
spec:
  template:
    spec:
      version: {{ .Values.k0s.version }}
      {{- if .Values.airgap }}
      downloadURL: {{ required ".Values.k0s.downloadURL is required on airgap deployment" .Values.k0s.downloadURL }}
      {{- end }}
      files:
        - path: /home/{{ .Values.ssh.user }}/.ssh/authorized_keys
          permissions: "0600"
          content: "{{ trim .Values.ssh.publicKey }}"
      preStartCommands:
        {{- if .Values.airgap }}
        - mkdir -p /var/lib/k0s/images
        - curl -fsL {{ required ".Values.k0s.bundleURL is required on airgap deployment" .Values.k0s.bundleURL }} -o /var/lib/k0s/images/k0s-airgap-bundle
        {{- end }}
        - chown {{ .Values.ssh.user }} /home/{{ .Values.ssh.user }}/.ssh/authorized_keys
