apiVersion: v2
name: external-secrets
description: A Helm chart to refer the official external-secrets helm chart
type: application
version: 0.11.0
appVersion: "0.11.0"
dependencies:
  - name: external-secrets
    version: 0.11.0
    repository: https://charts.external-secrets.io
