apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hmc.fullname" . }}-manager-role
  labels:
  {{- include "hmc.labels" . | nindent 4 }}
rules:
- apiGroups:
  - operator.cluster.x-k8s.io
  resources:
  - coreproviders
  - infrastructureproviders
  - bootstrapproviders
  - controlplaneproviders
  verbs:
  - get
  - list
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managedclusters
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managedclusters/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managedclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managements
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - accessmanagements
  - clustertemplatechains
  - servicetemplatechains
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - releases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - releases/status
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managements/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managements/status
  - accessmanagements/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - clustertemplates
  - servicetemplates
  - providertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - clustertemplates/finalizers
  - servicetemplates/finalizers
  - providertemplates/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - clustertemplates/status
  - servicetemplates/status
  - providertemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmcharts
  - helmrepositories
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - create
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsclusters
  - azureclusters
  - vsphereclusters
  - vspheremachines
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - credentials
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - credentials/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - credentials/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsclusterstaticidentities
  - awsclustercontrolleridentities
  - awsclusterroleidentities
  - azureclusteridentities
  - vsphereclusteridentities
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - config.projectsveltos.io
  resources:
  - profiles
  - clusterprofiles
  - clustersummaries
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - awsmanagedcontrolplanes
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - multiclusterservices
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - multiclusterservices/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - multiclusterservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - backups
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hmc.fullname" . }}-manager-secrets-reader-role
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "hmc.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
