apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hmc.fullname" . }}-manager-role
  labels:
  {{- include "hmc.labels" . | nindent 4 }}
rules:
- apiGroups:
  - operator.cluster.x-k8s.io
  resources:
  - coreproviders
  - infrastructureproviders
  - bootstrapproviders
  - controlplaneproviders
  verbs:
  - get
  - list
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - clusterdeployments
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - clusterdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - clusterdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managements
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - accessmanagements
  - clustertemplatechains
  - servicetemplatechains
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - releases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - releases/status
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managements/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managements/status
  - accessmanagements/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - clustertemplates
  - servicetemplates
  - providertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - clustertemplates/finalizers
  - servicetemplates/finalizers
  - providertemplates/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - clustertemplates/status
  - servicetemplates/status
  - providertemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmcharts
  - helmrepositories
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - create
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsclusters
  - azureclusters
  - vsphereclusters
  - vspheremachines
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - credentials
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - credentials/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - credentials/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsclusterstaticidentities
  - awsclustercontrolleridentities
  - awsclusterroleidentities
  - azureclusteridentities
  - vsphereclusteridentities
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - config.projectsveltos.io
  resources:
  - profiles
  - clusterprofiles
  - clustersummaries
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - multiclusterservices
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - multiclusterservices/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - multiclusterservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: {{ include "rbac.viewerVerbs" . | nindent 2 }}
  - create
# managementbackups-ctrl
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managementbackups
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managementbackups/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managementbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - namespaces
  verbs: {{ include "rbac.viewerVerbs" . | nindent 2 }}
  - create
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: {{ include "rbac.viewerVerbs" . | nindent 2 }}
  - create
  - delete
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs: {{ include "rbac.viewerVerbs" . | nindent 2 }}
  - create
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: {{ include "rbac.viewerVerbs" . | nindent 2 }}
  - create
- apiGroups:
  - velero.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - list
  - get
# managementbackups-ctrl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hmc.fullname" . }}-manager-secrets-reader-role
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "hmc.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
