apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: azure-dev
  namespace: ${NAMESPACE}
  labels:
    hmc.mirantis.com/component: hmc
spec:
  template: azure-standalone-cp-0-0-4
  credential: azure-cluster-identity-cred
  config:
    controlPlaneNumber: 1
    workersNumber: 1
    location: "westus"
    subscriptionID: "${AZURE_SUBSCRIPTION_ID}"
    controlPlane:
      vmSize: Standard_A4_v2
    worker:
      vmSize: Standard_A4_v2
    tenantID: "${AZURE_TENANT_ID}"
    clientID: "${AZURE_CLIENT_ID}"
    clientSecret: "${AZURE_CLIENT_SECRET}"
