apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: eks-dev
  namespace: ${NAMESPACE}
  labels:
    hmc.mirantis.com/component: hmc
spec:
  template: aws-eks-0-0-2
  credential: "aws-cluster-identity-cred"
  config:
    region: ${AWS_REGION}
    workersNumber: 1
