---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereClusterIdentity
metadata:
  name: vsphere-cluster-identity
  namespace: ${NAMESPACE}
  labels:
    hmc.mirantis.com/component: hmc
spec:
  secretName: vsphere-cluster-identity-secret
  allowedNamespaces:
    selector:
      matchLabels: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: vsphere-cluster-identity-secret
  namespace: ${NAMESPACE}
  labels:
    hmc.mirantis.com/component: hmc
stringData:
  username: ${VSPHERE_USER}
  password: ${VSPHERE_PASSWORD}
---
apiVersion: hmc.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: vsphere-cluster-identity-cred
  namespace: ${NAMESPACE}
  labels:
    hmc.mirantis.com/component: hmc
spec:
  description: vSphere credentials
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereClusterIdentity
    name: vsphere-cluster-identity
    namespace: ${NAMESPACE}
