apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: adopted-cluster-0-0-1
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: adopted-cluster
      version: 0.0.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: hmc-templates
