apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: adopted-cluster-0-0-4
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartName: adopted-cluster
    chartVersion: 0.0.4
