apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: aws-eks-0-0-2
  annotations:
    helm.sh/resource-policy: keep
  labels:
    hmc.mirantis.com/component: hmc
spec:
  helm:
    chartSpec:
      chart: aws-eks
      version: 0.0.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: hmc-templates
