apiVersion: hmc.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: cert-manager-1-16-2
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cert-manager
      version: 1.16.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: hmc-templates
