apiVersion: hmc.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-aws
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartName: cluster-api-provider-aws
    chartVersion: 0.1.2
