apiVersion: hmc.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-vsphere-0-0-5
  annotations:
    helm.sh/resource-policy: keep
  labels:
    hmc.mirantis.com/component: hmc
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-vsphere
      version: 0.0.5
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: hmc-templates
