apiVersion: hmc.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: external-secrets-0-11-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: external-secrets
      version: 0.11.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: hmc-templates
