apiVersion: hmc.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: hmc-0-0-5
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: hmc
      version: 0.0.5
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: hmc-templates
