apiVersion: hmc.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: projectsveltos-0-44-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: projectsveltos
      version: 0.44.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: hmc-templates
