apiVersion: hmc.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: projectsveltos-0-40-0
  labels:
    hmc.mirantis.com/release: hmc-0-0-3
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartName: projectsveltos
    chartVersion: 0.40.0
