apiVersion: hmc.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: velero-8-1-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: velero
      version: 8.1.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: hmc-templates
