apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: {{ include "cluster.name" . }}
  annotations:
    cluster.x-k8s.io/managed-by: k0smotron
  finalizers:
  - hmc.mirantis.com/cleanup
spec:
  {{- with .Values.clusterIdentity }}
  identityRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  networkSpec:
    vnet:
      resourceGroup: {{ .Values.resourceGroup }}
      name: {{ .Values.network.vnetName }}
#    subnets:
#      - name: {{ .Values.network.nodeSubnetName }}
#        role: node
#        routeTable:
#          name: {{ .Values.network.nodeRouteTableName }}
#        securityGroup:
#          name: {{ .Values.network.nodeSecurityGroupName }}
#      - name: {{ .Values.network.cpSubnetName }}
#        role: control-plane
#        routeTable:
#          name: {{ .Values.network.cpRouteTableName }}
#        securityGroup:
#          name: {{ .Values.network.cpSecurityGroupName }}
  location: {{ .Values.location }}
  {{- if .Values.bastion.enabled }}
  {{- with .Values.bastion.bastionSpec }}
  bastionSpec:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  subscriptionID: {{ .Values.subscriptionID }}
  resourceGroup: {{ .Values.resourceGroup }}
